[versions]
material3 = "1.11.0-alpha07"
navigation3 = "1.1.1"

[libraries]
compose.material3.windowsizeclass = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "material3" }
androidx.navigation3.ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }

# Android
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.13.0" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.2.0" }

materialkolor = { module = "com.materialkolor:material-kolor", version = "5.0.0-alpha07" }
