/// Metadata storage layer (SQLite-backed, future integration)
///
/// This module will provide metadata queries for:
/// - Space registry (id, name, created_at)
/// - Daily entries index (space_id, date, word_count)
/// - Task lists (space_id, task_id, title, completed)
///
/// Currently a placeholder. Future phases will integrate SQLDelight
/// to generate Kotlin code for KMP platforms.

// Schema (to be generated by SQLDelight):
//
// CREATE TABLE IF NOT EXISTS spaces (
//     id TEXT PRIMARY KEY,
//     name TEXT NOT NULL,
//     created_at INTEGER NOT NULL
// );
//
// CREATE TABLE IF NOT EXISTS daily_entries (
//     space_id TEXT NOT NULL,
//     date TEXT NOT NULL,
//     word_count INTEGER,
//     PRIMARY KEY (space_id, date),
//     FOREIGN KEY (space_id) REFERENCES spaces(id)
// );
//
// CREATE TABLE IF NOT EXISTS cas_index (
//     hash TEXT PRIMARY KEY,
//     size_bytes INTEGER,
//     created_at INTEGER
// );

pub struct MetadataStore {
    // Future: connection to SQLite database
    _marker: (),
}

impl MetadataStore {
    #[must_use]
    pub fn new() -> Self {
        MetadataStore { _marker: () }
    }
}

impl Default for MetadataStore {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_metadata_store_placeholder() {
        let _store = MetadataStore::new();
        // TODO: Add real tests once SQLDelight integration is complete
    }
}
